alias sudo='sudo '
alias gp='git pull'
alias gpp='git push'
alias ga='git add'
alias gaa='git add -A'
alias gb='git branch'
alias gch='git checkout'
alias ech='COMMIT_HASH=$(git rev-parse HEAD)'
alias gd='git diff'
alias gs='git status'
alias gl='git log'
function gc() { git commit -m "$*" ;}
function gg() { git grep "$*" -- ':!package-lock.json' ;}
function ggi() { git grep -i "$*" -- ':!package-lock.json' ;}
alias ll='LC_ALL=C ls -lAh --group-directories-first --color'
alias grep='grep --color=auto --exclude-dir=node_modules'
alias wtf='du -sch .[!.]* * | sort -h'
alias syu='sudo pacman -Syu && yay -Su --aur --ignore js78 --ignore pdf-decrypt'
alias syc='sudo pacman -Qdtq && sudo pacman -Rns $(pacman -Qdtq)'
alias pacman='sudo pacman'
alias list-empty-folders='find . -type d -empty'
alias cdd='cd "$(git rev-parse --show-toplevel)"'
